config {
    type: "table",
    database: dataform.projectConfig.vars.project + dataform.projectConfig.vars.env,
    schema: "d_" + dataform.projectConfig.vars.use_case + "_audit_eu_" + dataform.projectConfig.vars.env,
    disabled: true,
    tags: ["audit"]
}
WITH
  freshness AS (
    SELECT
      *,
      DATE_DIFF(CURRENT_DATE(), dummy_ingestion_date, DAY) AS delay
    FROM
      ${ref("t_rpt_template")}
  )
SELECT
  *
FROM
   freshness
WHERE
   delay <= 1
